version: '3.8'

services:
  telegram-bot:
    build: .
    container_name: tg_investagregator_bot
    restart: unless-stopped
    command: python -m test_main
    entrypoint: ./entrypoint.sh
    volumes:
      # Монтируем директорию для базы данных
      - ./bot_data:/code/data
    env_file:
      - .env